CREATE TABLE IF NOT EXISTS USERS (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 first_name VARCHAR(255) NOT NULL,
                                 last_name VARCHAR(255) NOT NULL,
                                 email VARCHAR(255) NOT NULL,
                                 budget DOUBLE PRECISION NULL,
                                 user_type_id INT NOT NULL
);