INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('BMW', 'SEDANE', 2, 1, 100000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('BMW', 'SUV', 2, 1.5, 120000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('BMW', 'HATCHBACK', 2, 0.8, 80000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('MERCEDES', 'SEDANE', 1.8, 1, 100000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('MERCEDES', 'SUV', 1.8, 1.5, 120000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('MERCEDES', 'HATCHBACK', 1.8, 0.8, 80000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('TOYOTA', 'SEDANE', 1.7, 1, 100000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('TOYOTA', 'SUV', 1.7, 1.3, 120000);
INSERT INTO public.pricing_coefficients (brand, category, mfg_date_coefficient, category_coefficient, base_price) VALUES ('TOYOTA', 'HATCHBACK', 1.7, 0.9, 80000);
